config/routes.rb
Rails.application.routes.draw do
  namespace :api, { format: 'json'} do
    namespace :v1 do
      resources :projects
    end
  end
  resources :predicate_numericals
  resources :sample_metadata_numericals
  resources :projects do
    resources :examinations do
      resources :samples 
    end
  end
  #objects に限り、post で import 処理を許可する
  resources 'projects', only: :index do
    collection { post :import }
  end
  resources 'examinations', only: :index do
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sample.rb
class Sample < ApplicationRecord
  belongs_to :examination
  has_many :sample_metadata_numerical
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]

  # GET /samples
  # GET /samples.json
  def index
#    @sample_metadata_numerical=SampleMetadataNumerical.where( sample_id:  params[:id])
    @sample_metadata_numerical=SampleMetadataNumerical.where( sample_id:  params[:sample_id])
#    @sample_metadata_numerical=SampleMetadataNumerical.all


  end

  # GET /samples/1
  # GET /samples/1.json
  def show
    @sample_metadata_numerical=SampleMetadataNumerical.where( sample_id:  params[:id])
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:examination_id, :title, :datetime)
    end
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/samples/_form.html.erb
<%= form_with(model: sample, local: true) do |form| %>
  <% if sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :examination_id %>
    <%= form.text_field :examination_id, id: :sample_examination_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :sample_title %>
  </div>

  <div class="field">
    <%= form.label :datetime %>
    <%= form.text_field :datetime, id: :sample_datetime %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Samples</h1>

<%= @id %>
<%= @define_at %>

<table>
  <thead>
    <tr>
      <th> predicate_numerical</th>
      <th> value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sample_metadata_numerical.each do |numerical| %>
      <tr>
        <td><%= numerical.predicate_numerical %></td>
        <td><%= numerical.value %></td>
<!--
        <td><%#= link_to 'Show', sample %></td>
        <td><%#= link_to 'Edit', edit_sample_path(sample) %></td>
        <td><%#= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Sample', new_sample_path %>

<%= link_to 'examinations' ,project_examinations_path(:project_id) %>
<%= link_to 'project' ,projects_path %>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Examination:</strong>
  <%= @sample.examination %>
</p>

<p>
  <strong>Title:</strong>
  <%= @sample.title %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @sample.define_at %>
</p>

<table>
  <thead>
    <tr>
      <th> predicate_numerical</th>
      <th> value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sample_metadata_numerical.each do |numerical| %>
      <tr>
        <td><%= numerical.predicate_numerical %></td>
        <td><%= numerical.value %></td>
<!--
        <td><%#= link_to 'Show', sample %></td>
        <td><%#= link_to 'Edit', edit_sample_path(sample) %></td>
        <td><%#= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
-->
      </tr>
    <% end %>
  </tbody>
</table>

<%#= link_to 'Edit', edit_sample_path(@sample) %> |
<%#= link_to 'Back', samples_path %>

<%= link_to 'examinations' ,project_examinations_path(params[:examination_id]) %>
<%= link_to 'project' ,projects_path %>