config/routes.rb
Rails.application.routes.draw do
  namespace :api, { format: 'json'} do
    namespace :v1 do
      resources :projects
    end
  end
  resources :predicate_numericals
  resources :sample_metadata_numericals
  resources :projects do
    resources :examinations do
      resources :samples 
    end
  end
  #objects に限り、post で import 処理を許可する
  resources 'projects', only: :index do
    collection { post :import }
  end
  resources 'examinations', only: :index do
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
require 'csv'
class Project < ApplicationRecord
  has_many :examinations

    def self.import(file)
      CSV.foreach(file.path, headers: true) do |row|

        project = new
        project.attributes = row.to_hash.slice(*updatable_attributes)

        project.save!

      end
    end

  def self.updatable_attributes
    ["alias","title","description","publication","expermien_id","analysis_id","client_id","collector_id","user_id"]
  end

end

app/controllers/api/v1/projects_controller.rb
#app/controllers/api/projects_contoroller.rb'
module Api
  module V1
    class ProjectsController < ApplicationController

      def index
        @projects = Project.all
        render json: @projects
      end
      def show
        @projects = Project.all
        render json: @projects
      end
      
      # POST /projects.json
      def create
            @project = Project.new(project_params)
            @project.save

      end
      private
      def project_params
        params.require(:project).permit(:alias, :title, :description, :publication, :expermien_id, :analysis_id, :client_id, :collector_id, :user_id)
      end


    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  def import
    Project.import(params[:file])
    redirect_to "/projects"
#     redirect_to root_url, notice:"インポート完了しました"
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:alias, :title, :description, :publication, :expermien_id, :analysis_id, :client_id, :collector_id, :user_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :alias %>
    <%= form.text_field :alias, id: :project_alias %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :project_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :project_description %>
  </div>

  <div class="field">
    <%= form.label :publication %>
    <%= form.text_field :publication, id: :project_publication %>
  </div>

  <div class="field">
    <%= form.label :expermien_id %>
    <%= form.text_field :expermien_id, id: :project_expermien_id %>
  </div>

  <div class="field">
    <%= form.label :analysis_id %>
    <%= form.text_field :analysis_id, id: :project_analysis_id %>
  </div>

  <div class="field">
    <%= form.label :client_id %>
    <%= form.text_field :client_id, id: :project_client_id %>
  </div>

  <div class="field">
    <%= form.label :collector_id %>
    <%= form.text_field :collector_id, id: :project_collector_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :project_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Alias</th>
      <th>Project Title</th>
      <th>project_id</th>
      <th># of samples</th>
      <th>Description</th>
      <th>Publication</th>
      <th>Expermien</th>
      <th>Analysis</th>
      <th>Client</th>
      <th>Collector</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.alias %></td>
        <td><%= link_to project.title, project_examinations_path(project.id)  %></td>

        <td><%= project.id %></td>
        <td><%= project.id %></td>

        <td><%= project.description %></td>
        <td><%= project.publication %></td>
        <td><%= project.expermien_id %></td>
        <td><%= project.analysis_id %></td>
        <td><%= project.client_id %></td>
        <td><%= project.collector_id %></td>
        <td><%= project.user_id %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= form_tag({controller: "projects", action: "import", method: "post"}, {multipart: true}) do %>
  <%= file_field_tag :file %>
  <%= submit_tag "データを一括インポート" %>
<% end %>
<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alias:</strong>
  <%= @project.alias %>
</p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Publication:</strong>
  <%= @project.publication %>
</p>

<p>
  <strong>Expermien:</strong>
  <%= @project.expermien_id %>
</p>

<p>
  <strong>Analysis:</strong>
  <%= @project.analysis_id %>
</p>

<p>
  <strong>Client:</strong>
  <%= @project.client_id %>
</p>

<p>
  <strong>Collector:</strong>
  <%= @project.collector_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @project.user_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>