config/routes.rb
Rails.application.routes.draw do
  namespace :api, { format: 'json'} do
    namespace :v1 do
      resources :projects
    end
  end
  resources :predicate_numericals
  resources :sample_metadata_numericals
  resources :projects do
    resources :examinations do
      resources :samples 
    end
  end
  #objects に限り、post で import 処理を許可する
  resources 'projects', only: :index do
    collection { post :import }
  end
  resources 'examinations', only: :index do
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/predicate_numerical.rb
class PredicateNumerical < ApplicationRecord
  belongs_to :sample_metadata_numerical
end

app/controllers/predicate_numericals_controller.rb
class PredicateNumericalsController < ApplicationController
  before_action :set_predicate_numerical, only: [:show, :edit, :update, :destroy]

  # GET /predicate_numericals
  # GET /predicate_numericals.json
  def index
    @predicate_numericals = PredicateNumerical.all
  end

  # GET /predicate_numericals/1
  # GET /predicate_numericals/1.json
  def show
  end

  # GET /predicate_numericals/new
  def new
    @predicate_numerical = PredicateNumerical.new
  end

  # GET /predicate_numericals/1/edit
  def edit
  end

  # POST /predicate_numericals
  # POST /predicate_numericals.json
  def create
    @predicate_numerical = PredicateNumerical.new(predicate_numerical_params)

    respond_to do |format|
      if @predicate_numerical.save
        format.html { redirect_to @predicate_numerical, notice: 'Predicate numerical was successfully created.' }
        format.json { render :show, status: :created, location: @predicate_numerical }
      else
        format.html { render :new }
        format.json { render json: @predicate_numerical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /predicate_numericals/1
  # PATCH/PUT /predicate_numericals/1.json
  def update
    respond_to do |format|
      if @predicate_numerical.update(predicate_numerical_params)
        format.html { redirect_to @predicate_numerical, notice: 'Predicate numerical was successfully updated.' }
        format.json { render :show, status: :ok, location: @predicate_numerical }
      else
        format.html { render :edit }
        format.json { render json: @predicate_numerical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /predicate_numericals/1
  # DELETE /predicate_numericals/1.json
  def destroy
    @predicate_numerical.destroy
    respond_to do |format|
      format.html { redirect_to predicate_numericals_url, notice: 'Predicate numerical was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_predicate_numerical
      @predicate_numerical = PredicateNumerical.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def predicate_numerical_params
      params.require(:predicate_numerical).permit(:name, :unit, :min, :max, :sample_metadata_numerical_id)
    end
end

app/helpers/predicate_numericals_helper.rb
module PredicateNumericalsHelper
end

app/views/predicate_numericals/_form.html.erb
<%= form_with(model: predicate_numerical, local: true) do |form| %>
  <% if predicate_numerical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(predicate_numerical.errors.count, "error") %> prohibited this predicate_numerical from being saved:</h2>

      <ul>
      <% predicate_numerical.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :predicate_numerical_name %>
  </div>

  <div class="field">
    <%= form.label :unit %>
    <%= form.text_field :unit, id: :predicate_numerical_unit %>
  </div>

  <div class="field">
    <%= form.label :min %>
    <%= form.text_field :min, id: :predicate_numerical_min %>
  </div>

  <div class="field">
    <%= form.label :max %>
    <%= form.text_field :max, id: :predicate_numerical_max %>
  </div>

  <div class="field">
    <%= form.label :sample_metadata_numerical_id %>
    <%= form.text_field :sample_metadata_numerical_id, id: :predicate_numerical_sample_metadata_numerical_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/predicate_numericals/edit.html.erb
<h1>Editing Predicate Numerical</h1>

<%= render 'form', predicate_numerical: @predicate_numerical %>

<%= link_to 'Show', @predicate_numerical %> |
<%= link_to 'Back', predicate_numericals_path %>

app/views/predicate_numericals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Predicate Numericals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Unit</th>
      <th>Min</th>
      <th>Max</th>
      <th>Sample metadata numerical</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @predicate_numericals.each do |predicate_numerical| %>
      <tr>
        <td><%= predicate_numerical.name %></td>
        <td><%= predicate_numerical.unit %></td>
        <td><%= predicate_numerical.min %></td>
        <td><%= predicate_numerical.max %></td>
        <td><%= predicate_numerical.sample_metadata_numerical %></td>
        <td><%= link_to 'Show', predicate_numerical %></td>
        <td><%= link_to 'Edit', edit_predicate_numerical_path(predicate_numerical) %></td>
        <td><%= link_to 'Destroy', predicate_numerical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Predicate Numerical', new_predicate_numerical_path %>

app/views/predicate_numericals/new.html.erb
<h1>New Predicate Numerical</h1>

<%= render 'form', predicate_numerical: @predicate_numerical %>

<%= link_to 'Back', predicate_numericals_path %>

app/views/predicate_numericals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @predicate_numerical.name %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @predicate_numerical.unit %>
</p>

<p>
  <strong>Min:</strong>
  <%= @predicate_numerical.min %>
</p>

<p>
  <strong>Max:</strong>
  <%= @predicate_numerical.max %>
</p>

<p>
  <strong>Sample metadata numerical:</strong>
  <%= @predicate_numerical.sample_metadata_numerical %>
</p>

<%= link_to 'Edit', edit_predicate_numerical_path(@predicate_numerical) %> |
<%= link_to 'Back', predicate_numericals_path %>