config/routes.rb
Rails.application.routes.draw do
  namespace :api, { format: 'json'} do
    namespace :v1 do
      resources :projects
    end
  end
  resources :predicate_numericals
  resources :sample_metadata_numericals
  resources :projects do
    resources :examinations do
      resources :samples 
    end
  end
  #objects に限り、post で import 処理を許可する
  resources 'projects', only: :index do
    collection { post :import }
  end
  resources 'examinations', only: :index do
    collection { post :import }
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/examination.rb
class Examination < ApplicationRecord
  belongs_to :project
  has_many :samples

    def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      # 登録する プロジェクトと検査（examination)を見つける
#      project = Project.where( title: row["projecttitle"])
#      @examination=Examination.where( project_id  project.id)
      @sample=Sample.where( id: row["sample_id"] )

      
      @metadata=SampleMetadataNumerical.new
      @metadata.predicate_numerical = row["predicate_numerical"]
      @metadata.value = row["value"]
      @metadata.sample_id = @sample.ids




#      project.each do | exm |
      
#      product = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
#      product.attributes = row.to_hash.slice(*updatable_attributes)
      # 保存する
#      product.save!
    end
    end

  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["project_id","sample_id","predicate_numerical","value"]
  end



end

app/controllers/examinations_controller.rb
class ExaminationsController < ApplicationController
  before_action :set_examination, only: [:show, :edit, :update, :destroy]

  # GET /examinations
  # GET /examinations.json
  def index
#    @examinations = Examination.all
#    @samples = Examination.where( :project_id => 1 )
    @examinations=Examination.where(project_id:  params[:project_id])
    @examinations.each  do | exm |
        @samples=Sample.where(  examination_id: exm.id)
    end
    @project_id = params[:project_id]

#    @samples = Sample.find(1)
  end

  # GET /examinations/1
  # GET /examinations/1.json
  def show
  end

  # GET /examinations/new
  def new
    #examination = Examination.new
    samples = Sample.all
  end

  # GET /examinations/1/edit
  def edit
  end

  def import
  # fileはtmpに自動で一時保存される
      Examination.import(params[:file])
#      redirect_to root_url, notice: "sampleを追加しました。"
      redirect_to "/examinations"
  end



  #GET number of sample
  #  def sample_count
  #       @examinations=Examination.where(  )
  #
  #         end
  #

  # POST /examinations
  # POST /examinations.json
  def create
    @examination = Examination.new(examination_params)

    respond_to do |format|
      if @examination.save
        format.html { redirect_to @examination, notice: 'Examination was successfully created.' }
        format.json { render :show, status: :created, location: @examination }
      else
        format.html { render :new }
        format.json { render json: @examination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /examinations/1
  # PATCH/PUT /examinations/1.json
  def update
    respond_to do |format|
      if @examination.update(examination_params)
        format.html { redirect_to @examination, notice: 'Examination was successfully updated.' }
        format.json { render :show, status: :ok, location: @examination }
      else
        format.html { render :edit }
        format.json { render json: @examination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /examinations/1
  # DELETE /examinations/1.json
  def destroy
    @examination.destroy
    respond_to do |format|
      format.html { redirect_to examinations_url, notice: 'Examination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_examination
      @examination = Examination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def examination_params
      params.require(:examination).permit(:project_id)
    end
end

app/helpers/examinations_helper.rb
module ExaminationsHelper
end

app/views/examinations/_form.html.erb
<%= form_with(model: examination, local: true) do |form| %>
  <% if examination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(examination.errors.count, "error") %> prohibited this examination from being saved:</h2>

      <ul>
      <% examination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, id: :examination_project_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/examinations/edit.html.erb
<h1>Editing Examination</h1>

<%= render 'form', examination: @examination %>

<%= link_to 'Show', @examination %> |
<%= link_to 'Back', examinations_path %>

app/views/examinations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Examinations</h1>

<table>
  <thead>
    <tr>
      <th>sample Title</th>
      <th>sample id</th>

      <th>define date</th>
      <th>#sample</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td><%= link_to sample.title,  project_examination_sample_path(@project_id, sample.examination_id, sample.id)  %></td>
        <td><%= sample.id  %></td>
        <td><%=  sample.define_at %></td>
        <td><%#= @nsample  %></td>
        <td><%= link_to 'Show', project_examination_samples_path(@project_id, sample.examination_id, sample.id) %></td>
        <td><%= link_to 'Edit', edit_project_examination_sample_path(:project_id, :id, sample.id) %></td>  
        <td><%#= link_to 'Destroy', examination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Examination', new_examination_path %>
<%= link_to 'Project', projects_path %>

<br>
<br>

<!-- ページの一番下に追加 -->
<%= form_tag import_examinations_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "インポート" %>
<% end %>

app/views/examinations/new.html.erb
<h1>New Examination</h1>

<%= render 'form', examination: @examination %>

<%= link_to 'Back', examinations_path %>

app/views/examinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @examination.project %>
</p>

<%= link_to 'Edit', edit_examination_path(@examination) %> |
<%= link_to 'Back', examinations_path %>